Document: edac-utils
Title: Debian edac-utils Manual
Author: <insert document author here>
Abstract: This manual describes what edac-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/edac-utils/edac-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/edac-utils/edac-utils.ps.gz

Format: text
Files: /usr/share/doc/edac-utils/edac-utils.text.gz

Format: HTML
Index: /usr/share/doc/edac-utils/html/index.html
Files: /usr/share/doc/edac-utils/html/*.html

  
